# Use an official Node runtime as a parent image
FROM node:20-alpine

WORKDIR /usr/src/app

# install dependencies
COPY backend/package*.json ./
RUN npm ci --only=production

# copy source
COPY backend/ ./

EXPOSE 3000

CMD ["node", "server.js"]
